'use client'
import React, { useRef, useState } from "react";
import buy from '@/app/styles/scss/index.module.scss'
import PaypalButton from "@/app/core/utils/PaypalButton";
import paypal from '@/app/styles/scss/index.module.scss'
import { PayPalScriptProvider } from "@paypal/react-paypal-js";
import CurrencySelect from "@/app/core/utils/CurrencySelect";
import Link from "next/link";

interface Props{
  clientId:string
}

const Section2 = ({clientId}:Props) => {
  const [currency,getCurrency] = useState("CAD")
  const [total,setTotal] = useState('')
  const price = 0.001
  const amountRef = useRef<HTMLInputElement>(null)

  const product ={
    description:"Generated by next13",
    price:30
  }

  const changeInput=()=>{
    if(amountRef.current){
      if(!Number.isNaN(parseInt(amountRef.current.value))){
        const amount = parseInt(amountRef.current.value)
        setTotal(String(amount*price))
      }
      console.log(total)
    }
  }
  return (
    <PayPalScriptProvider options={{"client-id":clientId,currency:currency}}>

    <section>
      <header>
        <div className={buy.Container}>
        <h1>
          <em>Get DPO tokens via fiat payment</em>
        </h1>
        <div className={buy.currencySelection}>
        <h3>Select Payment Currency</h3>
          <CurrencySelect />
        </div>
        <input ref={amountRef} min={10000} type="number" placeholder="Enter amount of tokens" />
        <p>{total}</p>
        <div className={paypal.paypalButtonContainer}>
        <PaypalButton product={product} />
        </div>
        <div>
          <hr />
          <small>or</small>
          <hr />
        </div>
        <h2>
          <em>Swap Exchange</em>
        </h2>
            <small>Swap DPO tokens with other tokens and vice versa</small>
        <button><Link href={"https://dpo-swap.vercel.app/"} target="_blank">Go To Swap</Link></button>
        </div>
      </header>
    </section>
    </PayPalScriptProvider>
  );
};

export default Section2;
